[package]
name = "Seminario_Rust-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-tarpaulin = "0.25.2"
random-number = "0.1.8"
strum = "0.24.1"
strum_macros = "0.24"
